import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const scriptPath = path.join(root, "scripts", "sync-content.mjs");
const dataDir = path.join(root, "src", "lib", "data");

assert.equal(fs.existsSync(scriptPath), true, "scripts/sync-content.mjs should exist");

const script = fs.readFileSync(scriptPath, "utf8");

assert.match(script, /symposium-content/, "script should reference symposium-content");
assert.match(script, /"dist"/, "script should reference dist");
assert.match(script, /"data"/, "script should reference data");
assert.match(script, /"assets"/, "script should reference assets");
assert.match(script, /"src", "lib", "data"/, "script should target src/lib/data");
assert.match(
  script,
  /"static",\s*"avatars",\s*"characters"/,
  "script should target static/avatars/characters"
);
assert.match(
  script,
  /"static", "branding"/,
  "script should target static/branding"
);
assert.match(
  script,
  /content-i18n\.js/,
  "script should preserve or regenerate content-i18n.js"
);
assert.match(
  script,
  /reading-i18n\.js/,
  "script should preserve or regenerate reading-i18n.js"
);

execFileSync(process.execPath, [scriptPath], {
  cwd: root,
  stdio: "pipe"
});

const contentI18nModulePath = path.join(dataDir, "content-i18n.js");
const readingI18nModulePath = path.join(dataDir, "reading-i18n.js");

assert.equal(
  fs.existsSync(contentI18nModulePath),
  true,
  "content-i18n.js should exist after sync"
);
assert.equal(
  fs.existsSync(readingI18nModulePath),
  true,
  "reading-i18n.js should exist after sync"
);

const contentI18nModule = fs.readFileSync(contentI18nModulePath, "utf8");
const readingI18nModule = fs.readFileSync(readingI18nModulePath, "utf8");

assert.match(
  contentI18nModule,
  /Generated by scripts\/sync-content\.mjs/,
  "content-i18n.js should be generated by the sync script"
);
assert.match(
  contentI18nModule,
  /annotationEnglishById/,
  "content-i18n.js should export the shared content i18n maps"
);
assert.match(
  readingI18nModule,
  /Generated by scripts\/sync-content\.mjs/,
  "reading-i18n.js should be generated by the sync script"
);
assert.match(
  readingI18nModule,
  /dialogEnglishTextById/,
  "reading-i18n.js should export the shared reading i18n maps"
);

console.log("content-sync-script.test.mjs passed");
