import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const projectRoot = path.resolve(import.meta.dirname, "..");
const gitCommonDir = execFileSync("git", ["rev-parse", "--git-common-dir"], {
	cwd: projectRoot,
	encoding: "utf8"
}).trim();
const canonicalRepoRoot = path.resolve(projectRoot, gitCommonDir, "..");
const contentRoot = path.resolve(canonicalRepoRoot, "..", "symposium-content");

const sourceDataDir = path.join(contentRoot, "dist", "data");
const sourceAssetsDir = path.join(contentRoot, "dist", "assets");

const targetDataDir = path.join(projectRoot, "src", "lib", "data");
const targetAvatarDir = path.join(projectRoot, "static", "avatars", "characters");
const targetBrandingDir = path.join(projectRoot, "static", "branding");

const generatedDataModuleTargets = [
	["content-i18n.json", "content-i18n.js"],
	["reading-i18n.json", "reading-i18n.js"]
];

function isIgnoredEntry(entry) {
	return entry.name.startsWith(".");
}

function assertDirectoryExists(directoryPath, label) {
	if (!fs.existsSync(directoryPath)) {
		throw new Error(`Missing ${label}: ${directoryPath}`);
	}
}

function resetDirectory(sourceDir, targetDir) {
	fs.rmSync(targetDir, { recursive: true, force: true });
	fs.mkdirSync(targetDir, { recursive: true });
	fs.cpSync(sourceDir, targetDir, { recursive: true });
}

function syncDataDirectory(sourceDir, targetDir) {
	fs.mkdirSync(targetDir, { recursive: true });

	const sourceEntries = fs
		.readdirSync(sourceDir, { withFileTypes: true })
		.filter((entry) => !isIgnoredEntry(entry));
	const sourceEntryNames = new Set(sourceEntries.map((entry) => entry.name));

	for (const entry of sourceEntries) {
		const sourcePath = path.join(sourceDir, entry.name);
		const targetPath = path.join(targetDir, entry.name);

		fs.rmSync(targetPath, { recursive: true, force: true });
		fs.cpSync(sourcePath, targetPath, { recursive: entry.isDirectory() });
	}

	for (const entry of fs.readdirSync(targetDir, { withFileTypes: true })) {
		const isSyncedJsonFile = entry.isFile() && entry.name.endsWith(".json");

		if (isSyncedJsonFile && !sourceEntryNames.has(entry.name)) {
			fs.rmSync(path.join(targetDir, entry.name), { force: true });
		}

		if (entry.isFile() && isIgnoredEntry(entry)) {
			fs.rmSync(path.join(targetDir, entry.name), { force: true });
		}
	}
}

function assertValidExportName(exportName, fileName) {
	if (!/^[$A-Z_a-z][$\w]*$/u.test(exportName)) {
		throw new Error(`Cannot generate export "${exportName}" from ${fileName}`);
	}
}

function getJSDocType(value) {
	if (!value || typeof value !== "object" || Array.isArray(value)) {
		return "unknown";
	}

	const recordValues = Object.values(value);

	if (recordValues.every((item) => typeof item === "string")) {
		return "Record<string, string>";
	}

	if (
		recordValues.every(
			(item) =>
				item &&
				typeof item === "object" &&
				!Array.isArray(item) &&
				typeof item.title === "string" &&
				typeof item.content === "string" &&
				Object.keys(item).every((key) => key === "title" || key === "content")
		)
	) {
		return "Record<string, { title: string, content: string }>";
	}

	return "Record<string, unknown>";
}

function writeGeneratedDataModule(jsonFileName, moduleFileName) {
	const jsonFilePath = path.join(targetDataDir, jsonFileName);
	const moduleFilePath = path.join(targetDataDir, moduleFileName);
	const json = JSON.parse(fs.readFileSync(jsonFilePath, "utf8"));
	const exportNames = Object.keys(json).sort();

	for (const exportName of exportNames) {
		assertValidExportName(exportName, jsonFileName);
	}

	const moduleLines = [
		"// Generated by scripts/sync-content.mjs. Do not edit directly.",
		""
	];

	if (exportNames.length > 0) {
		for (const exportName of exportNames) {
			moduleLines.push(`/** @type {${getJSDocType(json[exportName])}} */`);
			moduleLines.push(`export const ${exportName} = ${JSON.stringify(json[exportName], null, "\t")};`);
			moduleLines.push("");
		}
	}

	moduleLines.push("const data = {");

	for (const exportName of exportNames) {
		moduleLines.push(`\t${exportName},`);
	}

	moduleLines.push("};");
	moduleLines.push("");
	moduleLines.push("export default data;");
	moduleLines.push("");

	fs.writeFileSync(moduleFilePath, moduleLines.join("\n"), "utf8");
}

assertDirectoryExists(sourceDataDir, "source data directory");
assertDirectoryExists(sourceAssetsDir, "source assets directory");

syncDataDirectory(sourceDataDir, targetDataDir);

for (const [jsonFileName, moduleFileName] of generatedDataModuleTargets) {
	writeGeneratedDataModule(jsonFileName, moduleFileName);
}

resetDirectory(path.join(sourceAssetsDir, "avatars", "characters"), targetAvatarDir);
resetDirectory(path.join(sourceAssetsDir, "branding"), targetBrandingDir);

console.log("sync-content.mjs passed");
